;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-delete
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        keyboard-quit
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-copy-from-below
        ))
